{
  "language": "java",
  "os": [
      "linux"
  ],
  "branches": {
    "only": [
        "gh-pages"
    ]
  },
  env:
    global:
    # 我将其添加到了travis-ci的环境变量中
    #- GH_REF: https://github.com/XueXue-feng/basic-code.git
  ,
  "jdk": [
      "9"
  ]
}
